name: Continuous Integration (CI)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Add gradlew permission
        run: chmod +x gradlew

      - name: Run unit tests with coverage
        run: ./gradlew test jacocoTestReport

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/jacocoTestReport.xml

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: test  # Waits for tests to finish first
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4

      - name: Download JaCoCo coverage report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: jacoco-report

      - name: Verify JaCoCo report download (Debugging)
        run: |
          if [ -f jacoco-report/jacocoTestReport.xml ]; then
            echo "✅ JaCoCo XML report downloaded successfully!"
          else
            echo "❌ ERROR: JaCoCo XML report NOT found!"
            exit 1
          fi

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Hafizmuh18_tut-advpro
            -Dsonar.organization=hafizmuh18
            -Dsonar.coverage.jacoco.xmlReportPaths=jacoco-report/jacocoTestReport.xml
